### ISSUE TITLE
Download Enabler v5 incompatible

### ISSUE THREAD

**Issue by Exeedy** [SilicaAndPina/CEX-2-REX#6]
Download Enabler v5 isn't working anymore. Should it needs to be updated from theflow? or is it a bug?
Thanks silica

[EDIT]

Silica are you so kind and could you fork and update download enabler v5?
I already requested it under issues on TheFlow's github but he only close it.
I have nearly zero coding skills todo this for myself but the plugin is very usefull and i don't want to miss your dex version silica.

**Comment by MobCat** [comment]
Pretty much Every plugin i tested didn't work but NoNpDRM was hit or miss but mostley miss
And i think its a thing with the plugin devs that have to make plugins compatible for DEX not DEX compatible with CEX plugins

**Comment by SilicaAndPina** [comment]
Any plugin that uses *main probably won't work unless the developers add offsets for 3.65 DEX sceShell 

How typical of flow to just close it..
But Luckily Princess of Sleeping will probably fix it

**Comment by SilicaAndPina** [comment]
Here ya go:
https://drive.google.com/file/d/18IsMKISQQ4KRLM_toODyn_SoEHqFYFI_/view?usp=drivesdk

That should work under DEX

**Comment by Exeedy** [comment]
Thank you a thousand times!!!!

**Comment by SilicaAndPina** [comment]
Next release of downloadenabler should also work xD
