### ISSUE TITLE
No touch/controls after install

### ISSUE THREAD

**Issue by gabreek** [SilicaAndPina/CEX-2-REX#7]
Just instaled on my 3.65 updated enso and after reboot i cant unlock my vita because touch does not respond and cant even select turn off with digital controllers...
Can't use my vita at all

**Comment by SilicaAndPina** [comment]
Congratulations, you ignored the readme. and ran the cex2rex PSVITA version on a PSTV (despite it saying explicitly not to)

simple fix - restore system from safe mode, should reset boot_config, if that doesnt work. fully reinstall firmware .pup
